  
version: 0.2
env:
  secrets-manager:
    TelerikNugetFeedUserName: TelerikPrivateNugetFeed:Username
    TelerkNugetFeedPassword: TelerikPrivateNugetFeed:Password
phases:
  pre_build:
    commands:
      - printenv
      - sed -inuget.config "s/%TelerikNugetFeedUserName%/$TelerikNugetFeedUserName/" nuget.config
      - sed -inuget.config "s/%TelerkNugetFeedPassword%/$TelerkNugetFeedPassword/" nuget.config
      - dotnet restore 
  build:
    commands:
      - dotnet publish -c release -o ./build_output 
artifacts:
  files:
    - build_output/**/*