  
version: 0.2
env:
  secrets-manager:
    TELERIKPRIVATENUGETFEEDUSERNAME: TelerikPrivateNugetFeed:Username
    TELERIKPRIVATENUGETFEEDPASSWORD: TelerikPrivateNugetFeed:Password
phases:
  pre_build:
    commands:
      - export TELERIKPRIVATENUGETFEEDUSERNAME=$TelerikPrivateNugetFeedUsername
      - export TELERIKPRIVATENUGETFEEDPASSWORD=$TelerikPrivateNugetFeedPassword
      - echo $TelerikPrivateNugetFeedUsername
      - sed -inuget.config 's/%TelerikNugetFeedUserName%/$TELERIKPRIVATENUGETFEEDUSERNAME/' nuget.config
      - sed -inuget.config 's/%$TelerikPrivateNugetFeedPassword%/$TELERIKPRIVATENUGETFEEDPASSWORD/' nuget.config
      - dotnet restore 
  build:
    commands:
      - dotnet publish -c release -o ./build_output 
artifacts:
  files:
    - build_output/**/*
    - nuget.config
