  
version: 0.2
phases:
  pre_build:
    commands:
      - dotnet restore ACA.Classes
  build:
    commands:
      - dotnet publish -c release -o ./build_output ACA.Classes
artifacts:
  files:
    - ACA.Classes/build_output/**/*